c_sharp_basics_1
9inebar/Aleh_Hramovich_Application pull request #1
Opened 2023-06-02 12:03 UTC by 9inebar

2023-06-02 13:01 UTC, MariaEroshevich requested changes

2023-06-02 13:01 UTC, MariaEroshevich commented on .idea/.idea.Aleh_Hramovich_Application/.idea/.gitignore
> +# Default ignored files
move gitignore to folder with solution.

2023-06-02 13:01 UTC, MariaEroshevich commented on .idea/.idea.Aleh_Hramovich_Application/.idea/.gitignore
> +# Default ignored files
and .idea files also shouldn't be pushed to remote repository.

2023-06-02 19:02 UTC, 9inebar commented on .idea/.idea.Aleh_Hramovich_Application/.idea/.gitignore
> +# Default ignored files
@MariaEroshevich looks like it's already in the folder contacting sln file:
<img width="833" alt="Screenshot 2023-06-02 at 21 58 09" src="https://github.com/9inebar/Aleh_Hramovich_Application/assets/135224442/2694078c-b460-4722-bf6b-dc9365ddf2a8">

2023-06-02 19:22 UTC, MariaEroshevich requested changes

2023-06-02 19:22 UTC, MariaEroshevich commented on .gitignore
> +.idea
copy git ignore from the link https://gist.github.com/kmorcinek/2710267 and paste to your gitignore file.

2023-06-03 20:53 UTC, MariaEroshevich approved these changes

2023-06-05 08:22 UTC, merged